### ISSUE TITLE
Support to create ipv6 danm network with different netmask

### ISSUE THREAD

**Issue by ArunN85** [nokia/danm#147]
As of now in Danm3, pure ipv6 support is not present and also not able to create network with mask as /120.
Only /64 is allowed as of now Is this support available in DANM4. Also this danm network when created with /64 and /120, what all will be the changes with respect to the gateway for the POD's

**Comment by Levovar** [comment]
the correct statement is that up until /64 is allowed, not specifically only /64
/120 means 256 addresses. IPv4 is perfectly suitable IMO for such a network. can you elaborate on your use-case, why would you like to use IPv6 for such a small pool?

**Comment by Levovar** [comment]
BTW full IPv6 support was introduced with DANM 3.3

**Comment by ArunN85** [comment]
I wanted to plan the ipv6 network with /120 netmask and in some customer places these are used.
If my network plan has /120 as the netmask, then it will not be possible to define it. These kind of small subnets are used when there are multiple LANS needs to be configured for my telco network,

Which ip will danm ip consider as the gateway if it is /64 and /120 ?

**Comment by Levovar** [comment]
just to be clear: you state there are customer environments where IPv4 is entirely not allowed, but all you get is a /120 IPv6 subnet?

DANM doesn't overwrite the default GW, it just creates the IP, rest is up to kernel. If you want to set up IP routes you can do that via Spec.Options.Routes6, where you supply the GW IP

the reason we don't support smaller subnets than /64 is because the adresses are partly dynamically generated. /64 is the smallest subnet where we consider the chance for collision appropriately small.

in order to support smaller subnets, we need to support setting allocation pools for the Spec.Options.Net6 parameter. which is possible to do with an appropriate size limitation (meaning that the _maximum_  of the IPv6 allocation pool needs to be restricted)
so it is a possible enhancement

**Comment by ArunN85** [comment]
Yes..  i get /120 network.

**Comment by topranks** [comment]
You shouldn't be using subnets of that size dude.  Sorry if this is no help, I don't think it is a good idea for the project to support things which do not comply with the standards though.

**Comment by wallyatgithub** [comment]
Hi,

It is exciting to see you have done 2 merges.

So is there any more commit to occur, or, this feature is ready now?

Thanks a lot.

**Comment by Levovar** [comment]
> Hi,
> 
> It is exciting to see you have done 2 merges.
> 
> So is there any more commit to occur, or, this feature is ready now?
> 
> Thanks a lot.

mostly ready, but there will be still 2 more PRs
PR1: to optimize the time it takes to find the first free IP during dynamic allocations coming from huge allocation pools we will store the last allocated IP as a pointer, and start the next search from that index (contrary to the current "we always start from index0" algorithm)
PR2: documentation and schema update

but majority of the functionality is already developed, yes

**Comment by Levovar** [comment]
feautre is considered fully implemented from my side, so closing the Issue
