### ISSUE TITLE
IP leak for the delegated CNI plugin (Calico we use) when there are time-out issues

### ISSUE THREAD

**Issue by clivez** [nokia/danm#165]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 bug
> feature

**What happened**:
As a background, there is some kind of performance issue in the cluster.
When DANM invoked Calico to add interface to pod, Calico did not response in time (10s), but it did run the add process for the pod. After the waiting time-out, DANM did not create danmep for this calico interface and returned error. Then when dealing with the DEL operation, DANM will not invoke Calico to delete because there is no danmep about the interface, as a result, IP leak in Calico.

**What you expected to happen**:
A danmep should be created for the delegated CNI plugin even if the invoking time out, so an explicit DEL call can be performed when deleting the pod.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
have you opened a ticket on Calico why do their cleanup process depends on an additional CNI_DEL being done?
sure, we can workaround this in DANM, but the root cause is negligent handling inside their CNI :) Exception handling 101: do your best to return the state to "working" when an exception occurs. Depending on others to do it for you is a very bad habit
could try to address it upstream as well, but sure, existing logic could be also reworked inside DANM to address this specific case

**Comment by clivez** [comment]
Honestly speaking, I don't think this should be a Calico problem.
When adding, kubelet sent CNI_ADD to DANM, and DANM sent CNI_ADD to Calico;
Then on deleting, kubelet sent CNI_DEL to DANM, but DANM did not send CNI_DEL to Calico because missing of danmep for this interface. So I think this should be a DANM problem.
