### ISSUE TITLE
Proposal: default network

### ISSUE THREAD

**Issue by libesz** [nokia/danm#21]
The use-case I would like to raise here is to have a chance to successfully deploy applications without danm related annotations. This pretty much involves all common reusable components out there (i.e. community maintained helm charts, kubernetes addons like coredns or dashboard, etc.) and usually solved with other (more simple) CNI plugins.
If we could enhance danm to have some configuration option as a "default" network connectivity in certain namespaces, than it could be used for the Pods in the same ns which does not require any specific network access. Default danmnets could have some restrictions as needed.

**Comment by Levovar** [comment]
As discussed off-line:
- awesome idea! :)
- implementation shall be backward compatible and fully configurable: we do not wish to become a project which always attaches a default network to Pods, unless explicitly configured
- the solution could be the following: 1: if danm.k8s.io/interfaces is defined, always and only provision the required network connections; 2: if connections are not defined, read K8s API server for a network called "default" within the NS of the Pod 2A: if found, attach exactly one network interface according to the default DanmNet 2B: if not, throw the existing error

This could be a good step1 implementation

Additional enhancements could include:
- configurable name for what is considered as the "default" DanmNet
- regex matching instead of exact match: possibility to configure multiple default networks
