### ISSUE TITLE
IP HA support using keepAlived on  DANM

### ISSUE THREAD

**Issue by anannaya** [nokia/danm#33]
Hi,
I understand that i have a bit weird requirement,
**Back Ground:**
In IMS volte  from UE to GM interface does not work behind NAT(legacy implementation), So we are using DANM CNI plugin for direct connectivity for external connection. I use the multus to achieve the multiple interfaces with either(calico/flannel..) .

Since We need a highly available ip address for UE connectivity  , I use the keepAlived as a standard software to achieve this.I achieved this by keeping  keepAlived container inside a pod, which takes care of plumbing the HA ipaddress inside the pod on danm network interface.(NET_ADMIN capability required for keepalived container). With current DANM behavior 2  drawbacks 
                                  *   2 extra ip address is wasted on actual interface inside the pod
                                  * HA ip is not known to DANM ipam(bitarray)

Since DANM is going to be standard solution for some of the volte products. My proposal is introduce the one more entry in Annotation block to understand the HA So that we can address those 2 drawbacks.

Any suggestion would also be helpful to achieve common solution.  
Br,
Anand

**Comment by Levovar** [comment]
yes, I'm quite familiar with the "moving IP" conundrum of the CSCF network element :)

couple of things I would like to understand regarding your use-case before I come back with a counter-proposal

> In IMS volte from UE to GM interface does not work behind NAT(legacy implementation)
what is the exact reason? why can't an external connection be terminated at a VNF's loadbalancer?

> which takes care of plumbing the HA ipaddress inside the pod on danm network interface.(NET_ADMIN capability required for keepalived container).
So if I understood it right you "reserve" an IP from the same subnet by yourself, and you add the IP to the container's network interface in addition to the IP DANM provisions you.
Is this correct?
If yes, how does this IP differ from the "normal" one, how come it is high-available? How is traffic routed to this IP?
Other thing I would like to understand: why don't you simply provision the chosen "HA" IP via static IP allocation?

**Comment by anannaya** [comment]
`what is the exact reason? why can't an external connection be terminated at a VNF's loadbalancer?`
->>> Yes we need SIP understandable LB, I could share why and what are the challenges to achieve this offline if you need more information.

```
So if I understood it right you "reserve" an IP from the same subnet by yourself, and you add the IP to the container's network interface in addition to the IP DANM provisions you.
Is this correct?
```
->>> yes. But We don't need 2 extra ip address(active and partner pods) to wasted on that interface. I just want want DANM to create only the interface if the "HA" option is enabled in pod annotation block and put the entry in the danm ipam.

`If yes, how does this IP differ from the "normal" one, how come it is high-available? How is traffic routed to this IP? Other thing I would like to understand: why don't you simply provision the chosen "HA" IP via static IP allocation?`
->>> In IMS for all the external communication is static ip address.   I have 2 pods (cif & cif-partner) ,keepAlived vrrp communication configured between these 2 pods. HA ip moves between these 2 pods. The only requirement i have DANM ipam should aware of that HA ip.

**Comment by Levovar** [comment]
Ok, I understand the issue. Just needed a refresher, actually I think I already had this discussion at least two times in the past :)

To recap: I'm still on the opinion that while your use-case is unfortunately valid, and forced upon you by badly thought out standards; solving it is not the responsibility of a Kubernetes-level CNI framework.

For me, it is more of a platform level feature, **a layer on top of DANM**. Even if this functionality cannot be implemented in a "real", technical loadbalancer, from Kubernetes perspective this is still a "LoadBalancer" issue as per se.

And actually, such solutions already exist upstream! Instead of trying to force multiple IPs to the same interface, why don't you use keepalived as an ingress LoadBalancer, with DR instead of NATting?
For example as implemented by this project:
https://github.com/munnerz/keepalived-cloud-provider

IMO DR mode would ensure your use-case still works because no NATting is involved, and using the existing LoadBalancer type Kubernetes Service would have a more native feel to the solution, while would also keep responsibilities where they belong.

**Comment by anannaya** [comment]
`IMO DR mode would ensure your use-case still works because no NATting is involved, and using the existing LoadBalancer type Kubernetes Service would have a more native feel to the solution, while would also keep responsibilities where they belong.`
->>> I have experimented multiple options for BARE-METAL , So finally came to DANM.  Please share more info on this , I will try and share my feedback.

There are multiple reasons why we need  DANM / keepAlived inside the pod
1. If we use the keepalived on the Host ( Same way BCMT/NCMS provides) , then our solution would be always bound to host.
2. We use DANM only for external communication .i.e our internal pod-pod/kube-service communication 
can be through other CNIs like calico/flannel. I don't know if there is any standard defined from NOKIA point of view.
3. There  were too much coupling in our application about the HA ip movement , So keepAlived gives a way to make (vrrp_script) decison of IP failover .

**Comment by Levovar** [comment]
> Please share more info on this , I will try and share my feedback.

The linked project has a nice README, it describes all that is required to set it up in production.

> If we use the keepalived on the Host ( Same way BCMT/NCMS provides) , then our solution would be always bound to host.

Keepalived anyway only keeps one node "active" at any given time. It doesn't matter if you instantiate your instance of keepalived within the application Pod, or in a separate one

> We use DANM only for external communication .i.e our internal pod-pod/kube-service communication
can be through other CNIs like calico/flannel.

The "other" connections are also set-up by DANM, so you actually use DANM for all of your connections.
Regardless, this is orthogonal to your issue. If you don't need a Keepalived backed LoadBalancer for a Pod, don't create one for it.
DR will connect to your Pods first interface I guess, so the HA VIP will continue to forward traffic to only one interface.

> There were too much coupling in our application about the HA ip movement , So keepAlived gives a way to make (vrrp_script) decison of IP failover .

Sorry to say this, but we won't support a "workaround" functionality just because a legacy application is implemented in an archaic manner.
It is the application's job to transform its architecture to be cloud-native, not the cloud's job to adapt to one application.

Generally speaking: supporting provisioning the same to multiple interfaces, and provisioning multiple IPs to the same interface is a  use-case we don't want to support unless there is a very good reason for it.
The current solution needs to work together with the existing cloud orchestrator, and I personally very much don't want to open-up this configuration option, because it can lead to lot of misconfiguration, and user dissatisfaction with the majority of the user base.
And right now I don't see a reason why this should be done, when your use-case can be satisfied in a number of ways - albeit with more effort on your side.
