### ISSUE TITLE
How do we cleanup the static ip incase of blade H/W failure of worker node.

### ISSUE THREAD

**Issue by anannaya** [nokia/danm#61]
Once docker&kubelet is stopped on a host, the POD's which has static ip (from danm) associated with it does not move until the docker and kubelet is running on the same host on which the POD was initially brought up.

static ip assignment is not fully supported??  Can there be separate kubernetes controller(operator) to cleanup the danm endpoints along with  releasing the static ip associated with that endpoint.

**Comment by Levovar** [comment]
that has nothing to do with DANM. Kubernetes works in a central server - remote agents setup, Kubelet being the node agent.
Kubelet is the one invoking the CNI interface.

If you stop Kubelet, there is no one to invoke the CNI plugin, therefore no network provisioning operations can happen on the node

**Comment by anannaya** [comment]
@Levovar  Yes I can understand, But there will be a downtime until that machine comes up.
Just a suggestion Can we write some webhook in admission controller to check the Danm endpoints and check the pods  running status take the decision to cleanup the ipam.

Any suggestion ?

**Comment by Levovar** [comment]
there will be a downtime, but it does not necessarily mean that the Pod having the static IP is also down.
even if the Docker daemon is not running, to container can.
I'm not in favour or reaping these IPs, because  if the Pod having it assigned still runs, and we re-assign the same IP to another Pod at the same time, that will lead to problems.

On the flip side, when Kubelet comes back online, it will synch the status of the Pods. If a Pod died while it was down, I think / expect Kubelet to invoke a CNI_DEL for the Pod.
In that case the static IP will be freed.
