### ISSUE TITLE
Istio not work with DANM

### ISSUE THREAD

**Issue by clivez** [nokia/danm#72]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> bug
> feature

**What happened**:
I tested istio in my cluster with DANM as the network plugin, and the istio functions could not work properly.
I give the pods two interfaces, eth0 from calico (invoked by DANM) to communicate with k8s, eth1 from ipvlan backended danmnet, and create the service in DANM schema (indicating the service is working on eth1).
But seems istio could not work with this kind of "headless and selectorless Services", its traffic management functions do not take effort in this scene, it only works when there is selector in the spec of service, but when there is selector in the spec, traffic will go to eth0, not eth1 that I want.
So I want to know, is there anybody that has ever tried istio with DANM? Need there to be some special configuration? Or they do not compatible at all?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- danm version
- Kubernetes version (use `kubectl version`):
- danm configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
summoning @janosi 
I'm not that big of an Istio guy, but it might be the case an enhancement is needed in Istio to support selectorless services
even if this service would not be headless, you anyway could not use the ClusterIP with an IPVLAN backend

**Comment by janosi** [comment]
As I can see it from here, Istio in general has issues with headless services https://github.com/istio/istio/issues/7495

Then when it comes to danm and the support of storing pod IPs from "non-eth0" networks into DNS: indeed, we use headless+selectorless services. As a consequence, these services do not have an Endpoint created by k8s. In order to trigger the DNS controller we have "svcwatcher" in the danm solution: svcwatcher looks for new pods behind the Service, and creates the relevant Endpoints for those pods. Now, in theory (never tried, sorry), if you start using svcwatcher then it will create the Endpoints for your objects. At that point you will be approx. on the same level than with normal headless services from Istio's perspective . Though, as mentioned above, Istio in general has problems with headless services, so AFAIK only the solutions proposed in that Istio issue (creating ServiceEntry for these pods) would work. Indeed, it is manual work, to update these ServiceEntries. So, what I could imagine as a possible enhancement is an extension of svcwatcher (or a new component) that updates those ServiceEntries dynamically.

**Comment by Levovar** [comment]
Thansk for the analysis Laszló!
svcwatcher indeed creates and manages the EndPoints, I have verified that on a real K8s infra, so It should still work :)
just for my reference: what are these "ServiceEntry" objects? Are they K8s API objects, or something in Istio/Envoy?

**Comment by janosi** [comment]
ServiceEntry is an Istio specific thing, that helps in integrating "out of cluster" services into the service mesh.  Unfortunately, it seems headless k8s services have to be handled like that currently in Istio.
https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/

**Comment by Levovar** [comment]
I see! but it is a K8s CRD then, right; not an Istio specific REST server's API?
meaning, that we could support this use-case by still manipulating only the K8s API server

if yes, this definitely could be an optional feature, controlled via a new feature flag in the svcwatcher.

**Comment by janosi** [comment]
Ahha! I see your point now :) Yes, in a k8s based deployment Istio uses CRDs.

**Comment by Levovar** [comment]
Awesome!
so then yes, this is something which could be supported with a moderated svcwatcher enhancement even with current Istio

**Comment by clivez** [comment]
Seems we will be able to use DANM together with Istio in the near future, that is wonderful!

**Comment by Levovar** [comment]
at least in theory, yes :) but just an FYI, that I won't be able to take it in the foreseeable future. I already have a couple major enhancements in my pipeline

**Comment by clivez** [comment]
That's fine, I'm now just trying it for study. At least we will have a direction if we meet a real use case in the future.

**Comment by Asisranjan** [comment]
Hi @clivez and @Levovar 
I see this is in open state. I am exploring Istio and Danm for now. Can you have any update on it. Is this fixed.

Thanks
Asisranjan Nayak

**Comment by Levovar** [comment]
@Asisranjan I haven't tested it since, and we also haven't implemented this enhancement as it is a little bit lower prio item compared to others we have
it can happen Istio doesn't have a problem with headless services anymore, one could repeate the test scenario with the latest releases from both project
if the scenario still behaves the same, the enhancement is still also possible to be done in DANM svcwatcher. just a matter of contribution :)

**Comment by Levovar** [comment]
I'm not sure this ticket is still relevant, so closing it. Nowadays Istio CNI handles traffic redirection transparently on its own, and it is not based on Services.
It is now possible to include / exclude specific CIDR blocks  with Istio CNI specific Pod annotations, so IMO that should solve the issue

but if you still think a separate integration is needed please re-open!
